In [1]:
import torch
import torch.nn as nn
import torch.optim as optim


In [3]:
train_data = {
  'good': True,
  'bad': False,
  'happy': True,
  'sad': False,
  'not good': False,
  'not bad': True,
  'not happy': False,
  'not sad': True,
  'very good': True,
  'very bad': False,
  'very happy': True,
  'very sad': False,
  'i am happy': True,
  'this is good': True,
  'i am bad': False,
  'this is bad': False,
  'i am sad': False,
  'this is sad': False,
  'i am not happy': False,
  'this is not good': False,
  'i am not bad': True,
  'this is not sad': True,
  'i am very happy': True,
  'this is very good': True,
  'i am very bad': False,
  'this is very sad': False,
  'this is very happy': True,
  'i am good not bad': True,
  'this is good not bad': True,
  'i am bad not good': False,
  'i am good and happy': True,
  'this is not good and not happy': False,
  'i am not at all good': False,
  'i am not at all bad': True,
  'i am not at all happy': False,
  'this is not at all sad': True,
  'this is not at all happy': False,
  'i am good right now': True,
  'i am bad right now': False,
  'this is bad right now': False,
  'i am sad right now': False,
  'i was good earlier': True,
  'i was happy earlier': True,
  'i was bad earlier': False,
  'i was sad earlier': False,
  'i am very bad right now': False,
  'this is very good right now': True,
  'this is very sad right now': False,
  'this was bad earlier': False,
  'this was very good earlier': True,
  'this was very bad earlier': False,
  'this was very happy earlier': True,
  'this was very sad earlier': False,
  'i was good and not bad earlier': True,
  'i was not good and not happy earlier': False,
  'i am not at all bad or sad right now': True,
  'i am not at all good or happy right now': False,
  'this was not happy and not good earlier': False,
}

test_data = {
  'this is happy': True,
  'i am good': True,
  'this is not happy': False,
  'i am not good': False,
  'this is not bad': True,
  'i am not sad': True,
  'i am very good': True,
  'this is very bad': False,
  'i am very sad': False,
  'this is bad not good': False,
  'this is good and happy': True,
  'i am not good and not happy': False,
  'i am not at all sad': True,
  'this is not at all good': False,
  'this is not at all bad': True,
  'this is good right now': True,
  'this is sad right now': False,
  'this is very bad right now': False,
  'this was good earlier': True,
  'i was not happy and not good earlier': False,
}

# NLP Problems
1. Variable Sequence Length
2. Order Matters
3. Short and Long Term Context

In [14]:
# Bag of Words
# finding number of unique words

unique_words = set()

for key in train_data.keys():
    unique_words.update(key.split())

unique_words = list(sorted(unique_words))
print(unique_words)

['all', 'am', 'and', 'at', 'bad', 'earlier', 'good', 'happy', 'i', 'is', 'not', 'now', 'or', 'right', 'sad', 'this', 'very', 'was']


In [17]:
# sentence to bag of words
X_train = []
for key in train_data.keys():
    vector = [0] * len(unique_words)
    for word in key.split():
        vector[unique_words.index(word)] = vector[unique_words.index(word)] + 1
    X_train.append(vector)

for v, k in zip(X_train, train_data.keys()):
    print(v, k)



[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] good
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] bad
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] happy
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0] sad
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0] not good
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0] not bad
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0] not happy
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0] not sad
[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0] very good
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0] very bad
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0] very happy
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0] very sad
[0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0] i am happy
[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0] this is good
[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0] i am bad
[0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 

In [21]:
Y_train = list(map(int, train_data.values()))

print(Y_train)
print(len(unique_words))


[1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
18


In [24]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
Y_train = torch.tensor(Y_train, dtype=torch.float32).to(device)


Using mps device


In [33]:
class OneNeuronSequential(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Sequential(
            nn.Linear(len(unique_words), 32),
            nn.ReLU(),
            nn.Linear(32, 1),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        return self.linear(x)

model = OneNeuronSequential().to(device)
print(model(X_train))
print(Y_train)

tensor([[0.4916],
        [0.5295],
        [0.5084],
        [0.5057],
        [0.4930],
        [0.5139],
        [0.4987],
        [0.4860],
        [0.4917],
        [0.5190],
        [0.5131],
        [0.4968],
        [0.5196],
        [0.5062],
        [0.5373],
        [0.5419],
        [0.5138],
        [0.5082],
        [0.5100],
        [0.5056],
        [0.5324],
        [0.4940],
        [0.5216],
        [0.5090],
        [0.5380],
        [0.5038],
        [0.5282],
        [0.5163],
        [0.5183],
        [0.5163],
        [0.4723],
        [0.4884],
        [0.5160],
        [0.5416],
        [0.5335],
        [0.5029],
        [0.5301],
        [0.4842],
        [0.5135],
        [0.5301],
        [0.4836],
        [0.5300],
        [0.5267],
        [0.5365],
        [0.5321],
        [0.5154],
        [0.5144],
        [0.5007],
        [0.5720],
        [0.5343],
        [0.5603],
        [0.5333],
        [0.5292],
        [0.4991],
        [0.4815],
        [0

In [35]:
# loss function
loss_fn = nn.BCELoss()

# optimizer
optimizer = optim.Adam(model.parameters(), lr=0.01)

def evaluate(model, loss_fn, X, Y):
    with torch.no_grad():
        prediction = model(X)
        loss = loss_fn(prediction, Y.reshape(-1, 1))
        return loss

# training loop
for epoch in range(5000):
    optimizer.zero_grad()
    prediction = model(X_train)
    loss = loss_fn(prediction, Y_train.reshape(-1, 1))
    loss.backward()
    optimizer.step()
    if epoch % 100 == 0:
        print(f"Epoch {epoch} loss: {evaluate(model, loss_fn, X_train, Y_train)}")




Epoch 0 loss: 0.02934490516781807
Epoch 100 loss: 0.023916341364383698
Epoch 200 loss: 0.023910056799650192
Epoch 300 loss: 0.02390734665095806
Epoch 400 loss: 0.023905755952000618
Epoch 500 loss: 0.023904701694846153
Epoch 600 loss: 0.023904018104076385
Epoch 700 loss: 0.023903602734208107
Epoch 800 loss: 0.02390327863395214
Epoch 900 loss: 0.023903027176856995
Epoch 1000 loss: 0.023902826011180878
Epoch 1100 loss: 0.023902656510472298
Epoch 1200 loss: 0.023902527987957
Epoch 1300 loss: 0.023902658373117447
Epoch 1400 loss: 0.023902345448732376
Epoch 1500 loss: 0.023902352899312973
Epoch 1600 loss: 0.02390223741531372
Epoch 1700 loss: 0.023902133107185364
Epoch 1800 loss: 0.02390209212899208
Epoch 1900 loss: 0.023902375251054764
Epoch 2000 loss: 0.023903999477624893
Epoch 2100 loss: 0.023902546614408493
Epoch 2200 loss: 0.02390226162970066
Epoch 2300 loss: 0.02390209771692753
Epoch 2400 loss: 0.023901987820863724
Epoch 2500 loss: 0.023901917040348053
Epoch 2600 loss: 0.023901866748929

In [36]:
print(model(X_train))
print(Y_train)

tensor([[1.0000e+00],
        [6.1014e-09],
        [1.0000e+00],
        [2.7288e-09],
        [9.7908e-10],
        [1.0000e+00],
        [3.5088e-10],
        [1.0000e+00],
        [1.0000e+00],
        [6.5161e-12],
        [1.0000e+00],
        [6.0000e-13],
        [1.0000e+00],
        [1.0000e+00],
        [1.8906e-09],
        [1.3886e-08],
        [4.2506e-10],
        [3.4529e-09],
        [1.9628e-10],
        [9.7441e-08],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [4.2992e-12],
        [4.0380e-13],
        [1.0000e+00],
        [5.0109e-01],
        [1.0000e+00],
        [5.0109e-01],
        [1.0000e+00],
        [3.0585e-14],
        [4.0352e-13],
        [1.0000e+00],
        [3.1140e-14],
        [1.0000e+00],
        [3.1137e-10],
        [1.0000e+00],
        [9.8709e-13],
        [5.8748e-13],
        [9.8153e-14],
        [1.0000e+00],
        [1.0000e+00],
        [1.3385e-10],
        [6.2125e-12],
        [5

In [37]:
results = []
for op in model(X_train):
    if op > 0.5:
        results.append(1)
    else:
        results.append(0)

print(results)
print(Y_train)

[1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
tensor([1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
        0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 0.], device='mps:0')


In [39]:
!pip install scikit-learn

  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 26.8 MB/s eta 0:00:00a 0:00:01
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.9/24.9 MB 14.3 MB/s eta 0:00:0000:0100:01
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [41]:
print(results)
print(Y_train)

[1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0]
tensor([1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
        0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 0.], device='mps:0')


In [42]:
from sklearn.metrics import accuracy_score
print(accuracy_score(results, Y_train.tolist()))

0.9827586206896551


In [43]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(results, Y_train.tolist()))

[[31  0]
 [ 1 26]]


In [44]:
from sklearn.metrics import classification_report
print(classification_report(results, Y_train.tolist()))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98        31
           1       1.00      0.96      0.98        27

    accuracy                           0.98        58
   macro avg       0.98      0.98      0.98        58
weighted avg       0.98      0.98      0.98        58



In [45]:
print(unique_words)

['all', 'am', 'and', 'at', 'bad', 'earlier', 'good', 'happy', 'i', 'is', 'not', 'now', 'or', 'right', 'sad', 'this', 'very', 'was']


In [47]:
new_ip_good = "i am good not bad at all"
new_ip_bad = "i am bad not good at all"

new_ip_good_vector = [0] * len(unique_words)
for word in new_ip_good.split():
    new_ip_good_vector[unique_words.index(word)] = new_ip_good_vector[unique_words.index(word)] + 1

new_ip_bad_vector = [0] * len(unique_words)
for word in new_ip_bad.split():
    new_ip_bad_vector[unique_words.index(word)] = new_ip_bad_vector[unique_words.index(word)] + 1

print(new_ip_good_vector)
print(new_ip_bad_vector)


[1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0]


In [48]:
print(model(torch.tensor(new_ip_good_vector, dtype=torch.float32).to(device)))
print(model(torch.tensor(new_ip_bad_vector, dtype=torch.float32).to(device)))

tensor([0.9800], device='mps:0', grad_fn=<SigmoidBackward0>)
tensor([0.9800], device='mps:0', grad_fn=<SigmoidBackward0>)
